== Introduction

WildFly 8 (nee JBoss Application Server 7) is lightweight, flexible,
Java EE 7 compliant, polyglot, and open source application server.
This self-paced hands-on lab gets you introduced to the basic features of WildFly 8.

=== Start and Stop WildFly

==== Standalone and Managed Domain

WildFly 8 can be started in two different modes:

. A _standalone_ server is an independent instance. It can be started using `bin/standalone.sh` or `bin/standalone.bat` launch scripts.
+
. A _managed domain_ that allows you to run and manage a multi-server topology and manage multiple WildFly instances from a single control point. It can be started using `bin/domain.sh` or `bin/domain.bat` launch scripts.
+
A Domain Controller is the central management control point for the collection of servers in the `domain'.

==== Web Profile and Full Platform

Java EE defines _profiles_ that represent a configuration of the platform suited to a particular class of applications. The Java EE Web Profile is defined as a separate specification in the platform, and is defined as a subset of technologies contained in the platform and targeted toward the developers of modern web applications. WildFly supports both Web Profile and Full Platform by defininig `configuration profiles'. 

==== Multiple instances on the same machine (with port offset ?)

=== Configure Logging

. Change log levels of existing subsystems
+
. Change logging format of existing logger
+
. Create custom logger
+
. Where to copy custom logging handler ? (class loading)

